"""
TFLite Model Manager for FL Server

Generates and updates TFLite model with current global weights.
"""

import numpy as np
import tensorflow as tf
import os

# ── Model architecture (must match ESP32) ───────────────────────────────────
INPUT_DIM = 9
HIDDEN1 = 16
HIDDEN2 = 8
OUTPUT_DIM = 4

# Paths
MODEL_DIR = "tflite_models"
MODEL_PATH = os.path.join(MODEL_DIR, "fl_model.tflite")
HEADER_PATH = os.path.join(MODEL_DIR, "model_data.h")

def create_model():
    """Create Keras model with same architecture as ESP32."""
    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape=(INPUT_DIM,)),
        tf.keras.layers.Dense(HIDDEN1, activation='relu', name='hidden1'),
        tf.keras.layers.Dense(HIDDEN2, activation='relu', name='hidden2'),
        tf.keras.layers.Dense(OUTPUT_DIM, activation='softmax', name='output'),
    ])
    return model

def weights_to_keras_model(weights_list):
    """
    Convert FL server weight format to Keras model.
    
    weights_list format: [W1, b1, W2, b2, W3, b3]
    - W1: [INPUT_DIM, HIDDEN1]
    - b1: [HIDDEN1]
    - W2: [HIDDEN1, HIDDEN2]
    - b2: [HIDDEN2]
    - W3: [HIDDEN2, OUTPUT_DIM]
    - b3: [OUTPUT_DIM]
    """
    model = create_model()
    
    # Set weights
    model.get_layer('hidden1').set_weights([
        np.array(weights_list[0], dtype=np.float32),  # W1
        np.array(weights_list[1], dtype=np.float32),  # b1
    ])
    model.get_layer('hidden2').set_weights([
        np.array(weights_list[2], dtype=np.float32),  # W2
        np.array(weights_list[3], dtype=np.float32),  # b2
    ])
    model.get_layer('output').set_weights([
        np.array(weights_list[4], dtype=np.float32),  # W3
        np.array(weights_list[5], dtype=np.float32),  # b3
    ])
    
    return model

def convert_to_tflite(model):
    """Convert Keras model to TFLite format."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = []  # No quantization (float32)
    tflite_model = converter.convert()
    return tflite_model

def write_c_header(tflite_model, filename):
    """Write TFLite model as C header file."""
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    with open(filename, 'w') as f:
        f.write("/**\n")
        f.write(" * Auto-generated TFLite model data.\n")
        f.write(f" * Architecture: {INPUT_DIM} -> {HIDDEN1} -> {HIDDEN2} -> {OUTPUT_DIM}\n")
        f.write(f" * Total weights: {(INPUT_DIM*HIDDEN1+HIDDEN1) + (HIDDEN1*HIDDEN2+HIDDEN2) + (HIDDEN2*OUTPUT_DIM+OUTPUT_DIM)}\n")
        f.write(" *\n")
        f.write(" * Generated by: tflite_model_manager.py\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_DATA_H\n")
        f.write("#define MODEL_DATA_H\n\n")
        f.write(f"const unsigned int g_model_data_len = {len(tflite_model)};\n\n")
        f.write("alignas(8) const unsigned char g_model_data[] = {\n")

        for i, byte in enumerate(tflite_model):
            if i % 12 == 0:
                f.write("  ")
            f.write(f"0x{byte:02x}")
            if i < len(tflite_model) - 1:
                f.write(", ")
            if i % 12 == 11:
                f.write("\n")

        f.write("\n};\n\n")
        f.write("#endif  // MODEL_DATA_H\n")

def update_tflite_model(weights_list):
    """
    Update TFLite model with new weights from FL server.
    
    Args:
        weights_list: List of weight arrays [W1, b1, W2, b2, W3, b3]
    
    Returns:
        Path to generated TFLite file
    """
    # Create model with new weights
    model = weights_to_keras_model(weights_list)
    
    # Convert to TFLite
    tflite_model = convert_to_tflite(model)
    
    # Save .tflite file
    os.makedirs(MODEL_DIR, exist_ok=True)
    with open(MODEL_PATH, 'wb') as f:
        f.write(tflite_model)
    
    # Also generate C header for ESP32
    write_c_header(tflite_model, HEADER_PATH)
    
    print(f"[TFLite] Updated model: {MODEL_PATH} ({len(tflite_model)} bytes)")
    print(f"[TFLite] Generated header: {HEADER_PATH}")
    
    return MODEL_PATH

def get_tflite_model_path():
    """Get path to current TFLite model."""
    return MODEL_PATH

def get_model_data_header():
    """Read and return the C header file content."""
    if os.path.exists(HEADER_PATH):
        with open(HEADER_PATH, 'r') as f:
            return f.read()
    return None

# ── Test ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Test with random weights
    weights = [
        np.random.randn(INPUT_DIM, HIDDEN1).tolist(),  # W1
        np.zeros(HIDDEN1).tolist(),                      # b1
        np.random.randn(HIDDEN1, HIDDEN2).tolist(),     # W2
        np.zeros(HIDDEN2).tolist(),                      # b2
        np.random.randn(HIDDEN2, OUTPUT_DIM).tolist(),  # W3
        np.zeros(OUTPUT_DIM).tolist(),                   # b3
    ]
    
    path = update_tflite_model(weights)
    print(f"Test model saved to: {path}")
