"""
Generate TFLite model for ESP32 inference.

This script creates a TFLite model with the same architecture as the manual NN:
  - Input: 9 features (accelerometer + gyroscope)
  - Hidden 1: 16 neurons, ReLU
  - Hidden 2: 8 neurons, ReLU
  - Output: 4 classes, Softmax

Usage:
  python generate_tflite_model.py                 # Generate model_data.h
  python generate_tflite_model.py --print-tensors  # Show tensor indices
  python generate_tflite_model.py --weights W1.npy b1.npy ...  # Load custom weights

Output: model_data.h (C header file for Arduino)
"""

import numpy as np
import tensorflow as tf
import sys
import os

# ── Model architecture (must match ESP32 code) ───────────────────────────────
INPUT_DIM = 9
HIDDEN1 = 16
HIDDEN2 = 8
OUTPUT_DIM = 4

def create_model():
    """Create Keras model with same architecture as ESP32."""
    model = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape=(INPUT_DIM,)),
        tf.keras.layers.Dense(HIDDEN1, activation='relu', name='hidden1'),
        tf.keras.layers.Dense(HIDDEN2, activation='relu', name='hidden2'),
        tf.keras.layers.Dense(OUTPUT_DIM, activation='softmax', name='output'),
    ])
    return model

def convert_to_tflite(model):
    """Convert Keras model to TFLite format."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = []  # No quantization (float32)
    tflite_model = converter.convert()
    return tflite_model

def write_c_header(tflite_model, filename="model_data.h"):
    """Write TFLite model as C array header file."""
    with open(filename, 'w') as f:
        f.write("/**\n")
        f.write(" * Auto-generated TFLite model data.\n")
        f.write(f" * Architecture: {INPUT_DIM} -> {HIDDEN1} -> {HIDDEN2} -> {OUTPUT_DIM}\n")
        f.write(f" * Total weights: {(INPUT_DIM*HIDDEN1+HIDDEN1) + (HIDDEN1*HIDDEN2+HIDDEN2) + (HIDDEN2*OUTPUT_DIM+OUTPUT_DIM)}\n")
        f.write(" *\n")
        f.write(" * Generated by: generate_tflite_model.py\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_DATA_H\n")
        f.write("#define MODEL_DATA_H\n\n")
        f.write(f"const unsigned int g_model_data_len = {len(tflite_model)};\n\n")
        f.write("alignas(8) const unsigned char g_model_data[] = {\n")

        for i, byte in enumerate(tflite_model):
            if i % 12 == 0:
                f.write("  ")
            f.write(f"0x{byte:02x}")
            if i < len(tflite_model) - 1:
                f.write(", ")
            if i % 12 == 11:
                f.write("\n")

        f.write("\n};\n\n")
        f.write("#endif  // MODEL_DATA_H\n")

    print(f"[OK] Generated {filename} ({len(tflite_model)} bytes)")

def print_tensor_info(tflite_model):
    """Print tensor indices and shapes (for debugging)."""
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

    print("\n=== Tensor Information ===\n")
    print("Input tensor:")
    inp = interpreter.get_input_details()[0]
    print(f"  Index: {inp['index']}, Shape: {inp['shape']}, Dtype: {inp['dtype']}")

    print("\nOutput tensor:")
    out = interpreter.get_output_details()[0]
    print(f"  Index: {out['index']}, Shape: {out['shape']}, Dtype: {out['dtype']}")

    print("\nAll tensors:")
    for tensor in interpreter.get_tensor_details():
        name = tensor['name']
        shape = tensor['shape']
        idx = tensor['index']
        print(f"  [{idx}] {name}: shape={shape}")

    print("\n=== Weight Indices for inference_tflite.h ===")
    print("Update these in inference_tflite.h if they differ:")
    print("  W1_tensor = interpreter->tensor(X);  // W1: [9, 16]")
    print("  b1_tensor = interpreter->tensor(X);  // b1: [16]")
    print("  W2_tensor = interpreter->tensor(X);  // W2: [16, 8]")
    print("  b2_tensor = interpreter->tensor(X);  // b2: [8]")
    print("  W3_tensor = interpreter->tensor(X);  // W3: [8, 4]")
    print("  b3_tensor = interpreter->tensor(X);  // b3: [4]")

def main():
    print("=== TFLite Model Generator for ESP32 ===\n")

    # Create model
    model = create_model()
    model.summary()

    # Initialize with Xavier weights (same as ESP32 code)
    for layer in model.layers:
        if hasattr(layer, 'kernel'):
            fan_in, fan_out = layer.kernel.shape
            limit = np.sqrt(6.0 / (fan_in + fan_out))
            weights = np.random.uniform(-limit, limit, layer.kernel.shape).astype(np.float32)
            layer.kernel.assign(weights)
        if hasattr(layer, 'bias'):
            layer.bias.assign(tf.zeros_like(layer.bias))

    # Convert to TFLite
    tflite_model = convert_to_tflite(model)

    # Write C header
    write_c_header(tflite_model, "model_data.h")

    # Print tensor info if requested
    if "--print-tensors" in sys.argv:
        print_tensor_info(tflite_model)

    print("\n=== Next Steps ===")
    print("1. Copy model_data.h to FL_client_esp32_modular/")
    print("2. In FL_client_esp32_modular.ino, change:")
    print('   #include "inference.h"  ->  #include "inference_tflite.h"')
    print("3. Install 'TensorFlow Lite Micro' library in Arduino IDE")
    print("4. Upload to ESP32")

if __name__ == "__main__":
    main()
